name: Build

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    name: Go ${{ matrix.go }} sample
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Run tests
      run: make test

    - name: Upload test coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.txt
        fail_ci_if_error: true
        verbose: true

    - name: Run linter
      run: make lint

    - name: Run vulnerabilities scan
      run: make scan

  tag:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        WITH_V: true
        VERBOSE: true
        DEFAULT_BUMP: patch
