name: Run Tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.14', '1.15', '1.16', '1.17', '1.18' ]
    name: Go ${{ matrix.go }} sample
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Run tests
      run: make test

    - name: Upload test coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.go == '1.18'
      with:
        files: ./coverage.txt
        fail_ci_if_error: true
        verbose: true

    - name: Run linter
      run: make lint

    - name: Run vulnerabilities scan
      run: make scan
